---
- hosts: 
  - kafka_broker
  - kafka_rest
  - control_center
  - ksql
  - schema_registry
  - kafka_connect
  gather_facts: false
  tasks:
    - name: Check all passwords gone
      include_tasks: token_notpresent.yml
      loop:
      - { password: '{{kafka_broker_ldap_password}}', property_file: /etc/kafka/server.properties }
      - { password: '{{kafka_rest_ldap_password}}', property_file: /etc/kafka-rest/kafka-rest.properties }
      - { password: '{{control_center_ldap_password}}', property_file: /etc/kafka-rest/kafka-rest.properties }
      - { password: '{{ksql_ldap_password}}', property_file: /etc/ksqldb/ksql-server.properties }
      - { password: '{{schema_registry_ldap_password}}', property_file: /etc/schema-registry/schema-registry.properties }
      - { password: '{{kafka_connect_ldap_password}}', property_file: /etc/kafka/connect-distributed.properties }
